# Site settings
title: Greater Manchester Skeptics Society
email: web@gmss.uk
description: >
  The Greater Manchester Skeptics run the Manchester Skeptics in the Pub events, which are held twice each month.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gmss.uk" # the base hostname & protocol for your site
twitter_username: gmskeptics
#github_username:  gmss

# Build settings
markdown: kramdown

permalink: /blog/:title/